### ISSUE TITLE
[possible bug] ws remains detected after ws is blocked and site refresh

### ISSUE THREAD

**Issue by ghost** [mbnuqw/ws-detector#1]
FF 57.03 x64 with WSD 1.1.1 on W10 x64 b16299

Utilizing WE https://addons.mozilla.org/en-GB/firefox/addon/policy-control/ and blocking webSocket. 

Having policy-control disabled and thereby permitting webSocket  WSD is showing correctly in the address bar. Then enabling policy-control and blocking webSocket and then refreshing the webpage WSD is still present in the address bar and thus erroneously indicating webSocket as active.

Looking into the network console (WS tab) it shows that blocking webSocket through policy-control is effective, i.e. no webSocket is opened, yet WSD is still present in the address bar and thus (however) erroneously indicating webSocket as active.

**Comment by ghost** [comment]
Looks like been fixed with v1.2.2

**Comment by mbnuqw** [comment]
Yeah, just wanted to say about it )
